COMMAND_SIZE = 9
INT_SIZE = 8
ADD_OP = "add      "
OBJ_OP = "obj_obj  "
SYM_OP = "sym      "
SUB_OP = "sub      "
BYE_OP = "bye      "
DIV_OP = "div      "
END_OP = "stop     "
PORT = 35000
SERVER_ADDRESS = "localhost"
